version: '3.4'

services:
  conda_dev:
    container_name: nlp_dev
    image: nlp_env
    build: .
    volumes: 
     #this mounts local folder to docker container
      - .:/app
    tty: true
    stdin_open: true