version: '3.4'

services:
  geo_dev:
    image: geo_analysis_conda
    build: .
    volumes: 
     #this mounts local folder to docker container
      - .:/root/app
    working_dir: /root 
    tty: true
    stdin_open: true