version: '3.4'

services:
  graph_tool_dev:
    container_name: graph_tool_dev
    image: graph-tool_env
    build: .
    volumes: 
     #this mounts local folder to docker container
      - .:/root/app
    working_dir: /root 
    tty: true
    stdin_open: true