version: '3.4'

services:
  pymc_conda_dev:
    container_name: pymc_dev
    image: pymc_env
    build: .
    volumes: 
     #this mounts local folder to docker container
      - .:/root/app
    working_dir: /root 
    tty: true
    stdin_open: true